import { Roboto } from "next/font/google";
import "./globals.css";

const roborto = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],weight : ['400','500','700'] 
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roborto.variable}  antialiased`}
      >
        <main className="max-w-4xl mx-auto p-4">
          {children}

        </main>
      </body>
    </html>
  );
}
